server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/assessment
    username: catalin
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
      show-sql: true
  main:
    web-application-type: servlet